parameters:
#    dv_bourse.example.class: Dv\BourseBundle\Example

services:
#    dv_bourse.example:
#        class: %dv_bourse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
